packages:
  - 'packages/*'
  - 'playgrounds/*'

catalog:
  '@vitejs/plugin-vue': ^6.0.0
  typescript: ^5.7.3
  unplugin-external: ^0.1.0-beta.3
  vite: ^7.0.3
  vite-plugin-dts: ^4.5.0
  vue: ^3.5.17
